In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# For better plotting visuals
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("Set2")
print("Library imports successful!")

Library imports successful!

In [40]:
df = pd.read_csv('../data/insurance_data.csv')
print('Dataset loaded successfully')

Dataset loaded successfully

In [41]:
df.shape

(10000, 21)

In [42]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Province', 'VehicleType',
       'AnnualIncome', 'RiskScore', 'AnnualPremium', 'Deductible', 'NCD',
       'PastClaims', 'Claimed', 'ClaimAmount', 'TotalPremium', 'TotalClaims',
       'CoverType', 'AutoMake', 'VehicleModel', 'CustomValueEstimate',
       'ZipCode', 'TransactionDate'],
      dtype='object')

In [43]:
df.head()

,CustomerID,Age,Gender,Province,VehicleType,AnnualIncome,RiskScore,AnnualPremium,Deductible,NCD,...,Claimed,ClaimAmount,TotalPremium,TotalClaims,CoverType,AutoMake,VehicleModel,CustomValueEstimate,ZipCode,TransactionDate
0,AC-100000,56,Male,Addis Ababa,Sedan,147270,61,2346,500,30,...,False,0.0,2346,0.0,Comprehensive,Lifan,620,32238,10002,2024-05-10
1,AC-100001,69,Female,Addis Ababa,SUV,74640,57,2334,500,0,...,True,9883.0,2334,9883.0,Comprehensive,Suzuki,Grand Vitara,52510,10001,2024-08-13
2,AC-100002,46,Male,Oromia,Sedan,70555,42,1697,250,20,...,False,0.0,1697,0.0,Third Party Fire & Theft,Lifan,620,26523,20001,2025-03-17
3,AC-100003,32,Female,Somali,Sedan,89398,63,2370,500,20,...,True,12134.0,2370,12134.0,Comprehensive,Toyota,Corolla,27036,40005,2025-03-17
4,AC-100004,60,Female,Tigray,SUV,78475,69,2582,500,0,...,False,0.0,2582,0.0,Comprehensive,Toyota,RAV4,58348,50002,2024-11-10

In [44]:
df.isnull()

,CustomerID,Age,Gender,Province,VehicleType,AnnualIncome,RiskScore,AnnualPremium,Deductible,NCD,...,Claimed,ClaimAmount,TotalPremium,TotalClaims,CoverType,AutoMake,VehicleModel,CustomValueEstimate,ZipCode,TransactionDate
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [14]:
df.dtypes

CustomerID              object
Age                      int64
Gender                  object
Province                object
VehicleType             object
AnnualIncome             int64
RiskScore                int64
AnnualPremium            int64
Deductible               int64
NCD                      int64
PastClaims               int64
Claimed                   bool
ClaimAmount            float64
TotalPremium             int64
TotalClaims            float64
CoverType               object
AutoMake                object
VehicleModel            object
CustomValueEstimate      int64
ZipCode                  int64
TransactionDate         object
dtype: object

In [23]:
# Convert TransactionDate to datetime if it exists
if 'TransactionDate' in df.columns:
    df['TransactionDate'] = pd.to_datetime(df['TransactionDate'])
    print('Start Day'+str(df['TransactionDate'].min()))
    print('End Day'+str(df['TransactionDate'].max()))
    df['Year']=df['TransactionDate'].dt.year
    df['Month'] = df['TransactionDate'].dt.month
    df['Quarter'] = df['TransactionDate'].dt.quarter

Start Day2024-01-01 00:00:00
End Day2025-06-29 00:00:00

In [ ]:
#Categorical values are columns that contian values that we cannot do math on them

categorical_columns = ['Gender', 'Province', 'VehicleType', 'CoverType', 'AutoMake', 
                       'VehicleModel', 'Claimed']

In [34]:
numerical_cols = ['TotalPremium', 'TotalClaims', 'Age', 'AnnualIncome', 
                  'CustomValueEstimate', 'RiskScore']
for col in numerical_cols:
    if col in df.columns:
         if pd.api.types.is_numeric_dtype(df[col]):
            print(f"  {col}: {df[col].dtype} (correct)")
         else:
            print(f" {col}: {df[col].dtype} (should be numeric)")

  TotalPremium: int64 (correct)
  TotalClaims: float64 (correct)
  Age: int64 (correct)
  AnnualIncome: int64 (correct)
  CustomValueEstimate: int64 (correct)
  RiskScore: int64 (correct)

In [35]:
key_numerical = ['TotalPremium', 'TotalClaims', 'CustomValueEstimate', 
                 'Age', 'AnnualIncome', 'RiskScore']
existing_numerical = [col for col in key_numerical if col in df.columns]
print(df[existing_numerical].describe())

       TotalPremium   TotalClaims  CustomValueEstimate           Age  \
count  10000.000000  10000.000000         10000.000000  10000.000000
mean    2488.127900   1314.188500         35640.598700     46.683500
std      735.674491   3921.864903         22353.988238     16.717963
min      951.000000      0.000000          5022.000000     18.000000
25%     2028.000000      0.000000         21442.750000     32.000000
50%     2307.000000      0.000000         28522.000000     46.000000
75%     2676.000000      0.000000         46721.000000     61.000000
max     5105.000000  49623.000000        134914.000000     75.000000

       AnnualIncome     RiskScore
count   10000.00000  10000.000000
mean    79201.97390     58.140000
std     33039.93977     14.267486
min     17202.00000     15.000000
25%     56105.00000     48.000000
50%     72942.00000     57.000000
75%     95092.00000     67.000000
max    376916.00000     95.000000

In [36]:
#Loss Ratio
df['LossRatio'] = np.where(df['TotalPremium'] >0 , df['TotalClaims'] / df['TotalPremium'] , 0)
print(df['LossRatio'].describe())

count    10000.000000
mean         0.442770
std          1.252813
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         15.895383
Name: LossRatio, dtype: float64

In [37]:
#Margin
df['Margin'] = df['TotalPremium'] - df['TotalClaims']
print(df['Margin'].describe())

count    10000.000000
mean      1173.939400
std       3742.979999
min     -44594.000000
25%       1812.000000
50%       2165.000000
75%       2504.250000
max       5079.000000
Name: Margin, dtype: float64